version: "3.8"

services:
  postgresql:
    image: postgres:14
    hostname: postgresql
    ports:
      - 5432:5432
    environment:
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
